FROM docker.io/alpine:3.20 AS fibre
ADD https://github.com/celestiaorg/celestia-app/releases/download/v10.2.0-mocha/fibre_Linux_x86_64.tar.gz /tmp/fibre.tar.gz
RUN tar -xzf /tmp/fibre.tar.gz -C /bin fibre

# A dockerfile for the celestia validator in consensus layer
# Based on:
# https://github.com/celestiaorg/celestia-app/blob/main/Dockerfile
FROM docker.io/alpine:3.20

ENV CELESTIA_HOME=/root

RUN apk update && apk add --no-cache bash curl jq dasel gcompat

# Copy in the binary
COPY --from=ghcr.io/celestiaorg/celestia-app:v10.2.0-mocha /bin/celestia-appd /bin/celestia-appd
COPY --from=fibre /bin/fibre /bin/fibre

COPY ./run-validator.sh /opt/entrypoint.sh
COPY ./healthcheck-validator.sh /opt/healthcheck.sh

#  1317 is the default API server port
# 19090 is the remotely accessible port for gRPC
# 26656 is the default node p2p port
# 26657 is the default RPC port
EXPOSE 1317 19090 26656 26657

CMD /opt/entrypoint.sh
