services:
  validator:
    image: validator
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.validator
    environment:
      - NO_COLOR=1
      # amount of DA nodes to provision (default: 3)
      - NODE_COUNT=3
    ports:
      - 127.0.0.1:19090:9090 # grpc
      # TODO: uncomment and remove grpcwebproxy below, once CORS works with built-in grpc-web
      #- 127.0.0.1:18080:1317 # grpc-web
    volumes: &vols
      - credentials:/credentials
      - genesis:/genesis
    healthcheck: &healthcheck-validator
      # wait for validator to fund all keys
      test: celestia-appd query block --type height 5
      interval: 1s
      timeout: 10s
      start_period: 10s
      retries: 60

  grpcwebproxy:
    image: grpcwebproxy
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.grpcwebproxy
    command: --backend_addr=validator:9090 --run_tls_server=false --allow_all_origins
    ports:
      - 127.0.0.1:18080:8080
    depends_on:
      validator:
        condition: service_healthy
    # just so we can count it as healthy
    healthcheck:
      test: "true"
      interval: 1s

  node-0:
    image: node
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NO_COLOR=1
      # id of the DA node (default: 0)
      # each node should have a next natural number starting from 0
      - NODE_ID=0
      # the type of the node to run (default: bridge)
      # our tests rely on first node being a bridge node, with SKIP_AUTH enabled
      - NODE_TYPE=bridge
      # setting SKIP_AUTH to true disables the use of JWT for authentication
      - SKIP_AUTH=true
    ports:
      - 127.0.0.1:26658:26658
    volumes: *vols
    depends_on:
      validator:
        condition: service_healthy
    healthcheck: &healthcheck-node
      # wait for the node to start json-rpc server and sync a few headers.
      # tests wait for height >= 3 anyway, so don't report healthy before that.
      test: /opt/healthcheck.sh 3
      interval: 1s
      timeout: 10s
      start_period: 20s
      retries: 90

  node-1:
    image: node
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NO_COLOR=1
      - NODE_ID=1
    ports:
      - 127.0.0.1:36658:26658
    volumes: *vols
    depends_on: &depends-on-node-0
      validator:
        condition: service_healthy
      node-0:
        condition: service_healthy
    healthcheck: *healthcheck-node

  node-2:
    image: node
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - NO_COLOR=1
      - NODE_ID=2
      - NODE_TYPE=light
      - SKIP_AUTH=true
    ports:
      - 127.0.0.1:46658:26658
    volumes: *vols
    depends_on: *depends-on-node-0
    healthcheck: *healthcheck-node

  # Uncomment for another nodes
  # remember to adjust services.validator.environment
  # node-3:
  #   image: node
  #   platform: "linux/amd64"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.node
  #   environment:
  #     - NO_COLOR=1
  #     - NODE_ID=3
  #   ports:
  #     - 127.0.0.1:56658:26658
  #   volumes: *vols
  #   depends_on: *depends-on-node-0
  #   healthcheck: *healthcheck-node

  # This validator is started as a separate network, only to be able to test
  # transactions eviction cases. Thus it has low TTL and block size.
  # This network uses the same keys for nodes as the main one.
  validator-eviction-testing:
    image: validator
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.validator
    environment:
      - NO_COLOR=1
      - P2P_NETWORK=private-eviction-testing
      # amount of DA nodes to provision (default: 3)
      - NODE_COUNT=3
      # values from the eviction testing in celestia-app
      # https://github.com/celestiaorg/celestia-app/blob/v6.2.5-mocha/pkg/user/tx_client_test.go#L338
      - BLOCK_SIZE=2097152 # 2 * 1024 * 1024; 2mb
      - SQUARE_SIZE=64
      - MEMPOOL_TX_TTL=1
    ports:
      - 127.0.0.1:29090:9090
    volumes: *vols
    # it reuses the keys created by the main validator
    depends_on:
      validator:
        condition: service_healthy
    healthcheck: *healthcheck-validator

volumes:
  # local volume where node's credentials can persist
  credentials:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './credentials'
  # a temporary fs where the genesis hash is announced
  genesis:
    driver_opts:
      type: tmpfs
      device: tmpfs
